/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator 2.3.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * ChatMessageRequest.h
 *
 * 
 */

#ifndef ChatMessageRequest_H_
#define ChatMessageRequest_H_


#include "ModelBase.h"

#include <cpprest/details/basic_types.h>
#include "Object.h"

namespace com {
namespace knetikcloud {
namespace client {
namespace model {

/// <summary>
/// 
/// </summary>
class  ChatMessageRequest
    : public ModelBase
{
public:
    ChatMessageRequest();
    virtual ~ChatMessageRequest();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// ChatMessageRequest members

    /// <summary>
    /// The content of the message
    /// </summary>
    std::shared_ptr<Object> getContent() const;
        void setContent(std::shared_ptr<Object> value);
    /// <summary>
    /// The type of the message set by the client
    /// </summary>
    utility::string_t getMessageType() const;
        void setMessageType(utility::string_t value);

protected:
    std::shared_ptr<Object> m_Content;
        utility::string_t m_Message_type;
    };

}
}
}
}

#endif /* ChatMessageRequest_H_ */
