/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * DatabaseConfig.h
 *
 * 
 */

#ifndef DatabaseConfig_H_
#define DatabaseConfig_H_


#include "ModelBase.h"

#include "MongoDatabaseConfig.h"
#include "SqlDatabaseConfig.h"

namespace com {
namespace knetikcloud {
namespace client {
namespace model {

/// <summary>
/// 
/// </summary>
class  DatabaseConfig
    : public ModelBase
{
public:
    DatabaseConfig();
    virtual ~DatabaseConfig();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// DatabaseConfig members

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<MongoDatabaseConfig> getMongo() const;
    void setMongo(std::shared_ptr<MongoDatabaseConfig> value);
    bool mongoIsSet() const;
    void unsetMongo();
    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<SqlDatabaseConfig> getSql() const;
    void setSql(std::shared_ptr<SqlDatabaseConfig> value);
    bool sqlIsSet() const;
    void unsetSql();

protected:
    std::shared_ptr<MongoDatabaseConfig> m_Mongo;
    bool m_MongoIsSet;
std::shared_ptr<SqlDatabaseConfig> m_Sql;
    bool m_SqlIsSet;
};

}
}
}
}

#endif /* DatabaseConfig_H_ */
