/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator 2.2.3.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * Expirable.h
 *
 * 
 */

#ifndef Expirable_H_
#define Expirable_H_


#include "Behavior.h"
#include <cpprest/details/basic_types.h>

namespace com {
namespace knetikcloud {
namespace client {
namespace model {

/// <summary>
/// 
/// </summary>
class  Expirable
    : public Behavior
{
public:
    Expirable();
    virtual ~Expirable();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// Expirable members

    /// <summary>
    /// The length of time
    /// </summary>
    int32_t getTimeLength() const;
    bool timeLengthIsSet() const;
    void unsetTime_length();
    void setTimeLength(int32_t value);
    /// <summary>
    /// The unit of time
    /// </summary>
    utility::string_t getUnitOfTime() const;
    bool unitOfTimeIsSet() const;
    void unsetUnit_of_time();
    void setUnitOfTime(utility::string_t value);

protected:
    int32_t m_Time_length;
    bool m_Time_lengthIsSet;
    utility::string_t m_Unit_of_time;
    bool m_Unit_of_timeIsSet;
};

}
}
}
}

#endif /* Expirable_H_ */
