/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator 2.3.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



#include "FileGroupProperty.h"

namespace com {
namespace knetikcloud {
namespace client {
namespace model {

FileGroupProperty::FileGroupProperty()
{
    m_FilesIsSet = false;
}

FileGroupProperty::~FileGroupProperty()
{
}

void FileGroupProperty::validate()
{
    // TODO: implement validation
}

web::json::value FileGroupProperty::toJson() const
{
    web::json::value val = this->Property::toJson();

    {
        std::vector<web::json::value> jsonArray;
        for( auto& item : m_Files )
        {
            jsonArray.push_back(ModelBase::toJson(item));
        }
        if(jsonArray.size() > 0)
        {
            val[U("files")] = web::json::value::array(jsonArray);
        }
    }

    return val;
}

void FileGroupProperty::fromJson(web::json::value& val)
{
    this->Property::fromJson(val);

    {
        m_Files.clear();
        std::vector<web::json::value> jsonArray;
        if(val.has_field(U("files")))
        {
        for( auto& item : val[U("files")].as_array() )
        {
            if(item.is_null())
            {
                m_Files.push_back( std::shared_ptr<FileProperty>(nullptr) );
            }
            else
            {
                std::shared_ptr<FileProperty> newItem(new FileProperty());
                newItem->fromJson(item);
                m_Files.push_back( newItem );
            }
        }
        }
    }
}

void FileGroupProperty::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix[namePrefix.size() - 1] != U('.'))
    {
        namePrefix += U(".");
    }

    multipart->add(ModelBase::toHttpContent(namePrefix + U("type"), m_Type));
    {
        std::vector<web::json::value> jsonArray;
        for( auto& item : m_Files )
        {
            jsonArray.push_back(ModelBase::toJson(item));
        }
        
        if(jsonArray.size() > 0)
        {
            multipart->add(ModelBase::toHttpContent(namePrefix + U("files"), web::json::value::array(jsonArray), U("application/json")));
        }
    }
}

void FileGroupProperty::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix[namePrefix.size() - 1] != U('.'))
    {
        namePrefix += U(".");
    }

    setType(ModelBase::stringFromHttpContent(multipart->getContent(U("type"))));
    {
        m_Files.clear();
        if(multipart->hasContent(U("files")))
        {

        web::json::value jsonArray = web::json::value::parse(ModelBase::stringFromHttpContent(multipart->getContent(U("files"))));
        for( auto& item : jsonArray.as_array() )
        {
            if(item.is_null())
            {
                m_Files.push_back( std::shared_ptr<FileProperty>(nullptr) );
            }
            else
            {
                std::shared_ptr<FileProperty> newItem(new FileProperty());
                newItem->fromJson(item);
                m_Files.push_back( newItem );
            }
        }
        }
    }
}

std::vector<std::shared_ptr<FileProperty>>& FileGroupProperty::getFiles()
{
    return m_Files;
}

void FileGroupProperty::setFiles(std::vector<std::shared_ptr<FileProperty>> value)
{
    m_Files = value;
    m_FilesIsSet = true;
}
bool FileGroupProperty::filesIsSet() const
{
    return m_FilesIsSet;
}

void FileGroupProperty::unsetFiles()
{
    m_FilesIsSet = false;
}

}
}
}
}

