/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator 2.3.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



#include "GlobalResource.h"

namespace com {
namespace knetikcloud {
namespace client {
namespace model {

GlobalResource::GlobalResource()
{
    m_Definition = U("");
    m_DefinitionIsSet = false;
    m_Global_def_id = U("");
    m_Global_def_idIsSet = false;
    m_ScopesIsSet = false;
    m_Type = U("");
    m_TypeIsSet = false;
}

GlobalResource::~GlobalResource()
{
}

void GlobalResource::validate()
{
    // TODO: implement validation
}

web::json::value GlobalResource::toJson() const
{
    web::json::value val = web::json::value::object();

    if(m_DefinitionIsSet)
    {
        val[U("definition")] = ModelBase::toJson(m_Definition);
    }
    if(m_Global_def_idIsSet)
    {
        val[U("global_def_id")] = ModelBase::toJson(m_Global_def_id);
    }
    {
        std::vector<web::json::value> jsonArray;
        for( auto& item : m_Scopes )
        {
            web::json::value tmp = web::json::value::object();
            tmp[U("key")] = ModelBase::toJson(item.first);
            tmp[U("value")] = ModelBase::toJson(item.second);
            jsonArray.push_back(tmp);
        }
        if(jsonArray.size() > 0)
        {
            val[U("scopes")] = web::json::value::array(jsonArray);
        }
    }
    if(m_TypeIsSet)
    {
        val[U("type")] = ModelBase::toJson(m_Type);
    }

    return val;
}

void GlobalResource::fromJson(web::json::value& val)
{
    if(val.has_field(U("definition")))
    {
        setDefinition(ModelBase::stringFromJson(val[U("definition")]));
    }
    if(val.has_field(U("global_def_id")))
    {
        setGlobalDefId(ModelBase::stringFromJson(val[U("global_def_id")]));
    }
    {
        m_Scopes.clear();
        std::vector<web::json::value> jsonArray;
        if(val.has_field(U("scopes")))
        {
        for( auto& item : val[U("scopes")].as_array() )
        {  
            utility::string_t key;
            if(item.has_field(U("key")))
            {
                key = ModelBase::stringFromJson(item[U("key")]);
            }
            if(item.is_null())
            {
                m_Scopes.insert(std::pair<utility::string_t,std::shared_ptr<ExpressionResource>>( key, std::shared_ptr<ExpressionResource>(nullptr) ));
            }
            else
            {
                std::shared_ptr<ExpressionResource> newItem(new ExpressionResource());
                newItem->fromJson(item[U("value")]);
                m_Scopes.insert(std::pair<utility::string_t,std::shared_ptr<ExpressionResource>>( key, newItem ));
            }
        }
        }
    }
    if(val.has_field(U("type")))
    {
        setType(ModelBase::stringFromJson(val[U("type")]));
    }
}

void GlobalResource::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix[namePrefix.size() - 1] != U('.'))
    {
        namePrefix += U(".");
    }

    if(m_DefinitionIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + U("definition"), m_Definition));
        
    }
    if(m_Global_def_idIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + U("global_def_id"), m_Global_def_id));
        
    }
    {
        std::vector<web::json::value> jsonArray;
        for( auto& item : m_Scopes )
        {
            web::json::value tmp = web::json::value::object();
            tmp[U("key")] = ModelBase::toJson(item.first);
            tmp[U("value")] = ModelBase::toJson(item.second);
            jsonArray.push_back(tmp);
        }
        
        if(jsonArray.size() > 0)
        {
            multipart->add(ModelBase::toHttpContent(namePrefix + U("scopes"), web::json::value::array(jsonArray), U("application/json")));
        }
    }
    if(m_TypeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + U("type"), m_Type));
        
    }
}

void GlobalResource::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix[namePrefix.size() - 1] != U('.'))
    {
        namePrefix += U(".");
    }

    if(multipart->hasContent(U("definition")))
    {
        setDefinition(ModelBase::stringFromHttpContent(multipart->getContent(U("definition"))));
    }
    if(multipart->hasContent(U("global_def_id")))
    {
        setGlobalDefId(ModelBase::stringFromHttpContent(multipart->getContent(U("global_def_id"))));
    }
    {
        m_Scopes.clear();
        if(multipart->hasContent(U("scopes")))
        {

        web::json::value jsonArray = web::json::value::parse(ModelBase::stringFromHttpContent(multipart->getContent(U("scopes"))));
        for( auto& item : jsonArray.as_array() )
        {
            utility::string_t key;
            if(item.has_field(U("key")))
            {
                key = ModelBase::stringFromJson(item[U("key")]);
            }
            if(item.is_null())
            {
                m_Scopes.insert(std::pair<utility::string_t,std::shared_ptr<ExpressionResource>>( key, std::shared_ptr<ExpressionResource>(nullptr) ));
            }
            else
            {
                std::shared_ptr<ExpressionResource> newItem(new ExpressionResource());
                newItem->fromJson(item[U("value")]);
                m_Scopes.insert(std::pair<utility::string_t,std::shared_ptr<ExpressionResource>>( key, newItem ));
            }
        }
        }
    }
    if(multipart->hasContent(U("type")))
    {
        setType(ModelBase::stringFromHttpContent(multipart->getContent(U("type"))));
    }
}

utility::string_t GlobalResource::getDefinition() const
{
    return m_Definition;
}


void GlobalResource::setDefinition(utility::string_t value)
{
    m_Definition = value;
    m_DefinitionIsSet = true;
}
bool GlobalResource::definitionIsSet() const
{
    return m_DefinitionIsSet;
}

void GlobalResource::unsetDefinition()
{
    m_DefinitionIsSet = false;
}

utility::string_t GlobalResource::getGlobalDefId() const
{
    return m_Global_def_id;
}


void GlobalResource::setGlobalDefId(utility::string_t value)
{
    m_Global_def_id = value;
    m_Global_def_idIsSet = true;
}
bool GlobalResource::globalDefIdIsSet() const
{
    return m_Global_def_idIsSet;
}

void GlobalResource::unsetGlobal_def_id()
{
    m_Global_def_idIsSet = false;
}

std::map<utility::string_t, std::shared_ptr<ExpressionResource>>& GlobalResource::getScopes()
{
    return m_Scopes;
}

void GlobalResource::setScopes(std::map<utility::string_t, std::shared_ptr<ExpressionResource>> value)
{
    m_Scopes = value;
    m_ScopesIsSet = true;
}
bool GlobalResource::scopesIsSet() const
{
    return m_ScopesIsSet;
}

void GlobalResource::unsetScopes()
{
    m_ScopesIsSet = false;
}

utility::string_t GlobalResource::getType() const
{
    return m_Type;
}


void GlobalResource::setType(utility::string_t value)
{
    m_Type = value;
    m_TypeIsSet = true;
}
bool GlobalResource::typeIsSet() const
{
    return m_TypeIsSet;
}

void GlobalResource::unsetType()
{
    m_TypeIsSet = false;
}

}
}
}
}

