/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator 2.3.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * MapProperty.h
 *
 * 
 */

#ifndef MapProperty_H_
#define MapProperty_H_


#include <cpprest/details/basic_types.h>
#include <map>
#include <vector>
#include "Property.h"

namespace com {
namespace knetikcloud {
namespace client {
namespace model {

/// <summary>
/// 
/// </summary>
class  MapProperty
    : public Property
{
public:
    MapProperty();
    virtual ~MapProperty();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// MapProperty members

    /// <summary>
    /// A map/object of string to sub-property
    /// </summary>
    std::map<utility::string_t, std::shared_ptr<Property>>& getMap();
        void setMap(std::map<utility::string_t, std::shared_ptr<Property>> value);

protected:
    std::map<utility::string_t, std::shared_ptr<Property>> m_map;
    };

}
}
}
}

#endif /* MapProperty_H_ */
