/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator 2.3.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * NotificationUserTypeResource.h
 *
 * 
 */

#ifndef NotificationUserTypeResource_H_
#define NotificationUserTypeResource_H_


#include "ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace com {
namespace knetikcloud {
namespace client {
namespace model {

/// <summary>
/// 
/// </summary>
class  NotificationUserTypeResource
    : public ModelBase
{
public:
    NotificationUserTypeResource();
    virtual ~NotificationUserTypeResource();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// NotificationUserTypeResource members

    /// <summary>
    /// Whether the user has muted direct notification of this type. Notifications can still be retrieved via the api
    /// </summary>
    bool getSilenced() const;
    bool silencedIsSet() const;
    void unsetSilenced();
    void setSilenced(bool value);
    /// <summary>
    /// The notification type id
    /// </summary>
    utility::string_t getType() const;
    bool typeIsSet() const;
    void unsetType();
    void setType(utility::string_t value);
    /// <summary>
    /// The user&#39;s id
    /// </summary>
    int32_t getUserId() const;
    bool userIdIsSet() const;
    void unsetUser_id();
    void setUserId(int32_t value);

protected:
    bool m_Silenced;
    bool m_SilencedIsSet;
    utility::string_t m_Type;
    bool m_TypeIsSet;
    int32_t m_User_id;
    bool m_User_idIsSet;
};

}
}
}
}

#endif /* NotificationUserTypeResource_H_ */
