/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * S3Config.h
 *
 * 
 */

#ifndef S3Config_H_
#define S3Config_H_


#include "ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace com {
namespace knetikcloud {
namespace client {
namespace model {

/// <summary>
/// 
/// </summary>
class  S3Config
    : public ModelBase
{
public:
    S3Config();
    virtual ~S3Config();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// S3Config members

    /// <summary>
    /// 
    /// </summary>
    utility::string_t getBucketName() const;
    void setBucketName(utility::string_t value);
    bool bucket_nameIsSet() const;
    void unsetBucket_name();
    /// <summary>
    /// 
    /// </summary>
    utility::string_t getCdnUrl() const;
    void setCdnUrl(utility::string_t value);
    bool cdn_urlIsSet() const;
    void unsetCdn_url();
    /// <summary>
    /// 
    /// </summary>
    utility::string_t getRegion() const;
    void setRegion(utility::string_t value);
    bool regionIsSet() const;
    void unsetRegion();
    /// <summary>
    /// 
    /// </summary>
    utility::string_t getUploadPrefix() const;
    void setUploadPrefix(utility::string_t value);
    bool upload_prefixIsSet() const;
    void unsetUpload_prefix();

protected:
    utility::string_t m_Bucket_name;
    bool m_Bucket_nameIsSet;
utility::string_t m_Cdn_url;
    bool m_Cdn_urlIsSet;
utility::string_t m_Region;
    bool m_RegionIsSet;
utility::string_t m_Upload_prefix;
    bool m_Upload_prefixIsSet;
};

}
}
}
}

#endif /* S3Config_H_ */
