/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * SubscriptionPlan.h
 *
 * 
 */

#ifndef SubscriptionPlan_H_
#define SubscriptionPlan_H_


#include "ModelBase.h"

#include <cpprest/details/basic_types.h>
#include <map>
#include <vector>
#include "Property.h"

namespace com {
namespace knetikcloud {
namespace client {
namespace model {

/// <summary>
/// 
/// </summary>
class  SubscriptionPlan
    : public ModelBase
{
public:
    SubscriptionPlan();
    virtual ~SubscriptionPlan();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// SubscriptionPlan members

    /// <summary>
    /// 
    /// </summary>
    std::map<utility::string_t, std::shared_ptr<Property>>& getAdditionalProperties();
    bool additional_propertiesIsSet() const;
    void unsetAdditional_properties();
    /// <summary>
    /// 
    /// </summary>
    utility::string_t getAvailability() const;
    void setAvailability(utility::string_t value);
    bool availabilityIsSet() const;
    void unsetAvailability();
    /// <summary>
    /// 
    /// </summary>
    int32_t getBillGraceDays() const;
    void setBillGraceDays(int32_t value);
    bool bill_grace_daysIsSet() const;
    void unsetBill_grace_days();
    /// <summary>
    /// 
    /// </summary>
    bool getConsolidated() const;
    void setConsolidated(bool value);
    bool consolidatedIsSet() const;
    void unsetConsolidated();
    /// <summary>
    /// 
    /// </summary>
    int32_t getFirstBill() const;
    void setFirstBill(int32_t value);
    bool first_billIsSet() const;
    void unsetFirst_bill();
    /// <summary>
    /// 
    /// </summary>
    utility::string_t getFirstBillUnitOfTime() const;
    void setFirstBillUnitOfTime(utility::string_t value);
    bool first_bill_unit_of_timeIsSet() const;
    void unsetFirst_bill_unit_of_time();
    /// <summary>
    /// 
    /// </summary>
    utility::string_t getId() const;
    void setId(utility::string_t value);
    bool idIsSet() const;
    void unsetId();
    /// <summary>
    /// 
    /// </summary>
    utility::string_t getLatePaymentSku() const;
    void setLatePaymentSku(utility::string_t value);
    bool late_payment_skuIsSet() const;
    void unsetLate_payment_sku();
    /// <summary>
    /// 
    /// </summary>
    bool getLocked() const;
    void setLocked(bool value);
    bool lockedIsSet() const;
    void unsetLocked();
    /// <summary>
    /// 
    /// </summary>
    int32_t getMaxAutoRenew() const;
    void setMaxAutoRenew(int32_t value);
    bool max_auto_renewIsSet() const;
    void unsetMax_auto_renew();
    /// <summary>
    /// 
    /// </summary>
    int32_t getMaxBillAttempts() const;
    void setMaxBillAttempts(int32_t value);
    bool max_bill_attemptsIsSet() const;
    void unsetMax_bill_attempts();
    /// <summary>
    /// 
    /// </summary>
    utility::string_t getMigrationPlan() const;
    void setMigrationPlan(utility::string_t value);
    bool migration_planIsSet() const;
    void unsetMigration_plan();
    /// <summary>
    /// 
    /// </summary>
    int32_t getMinimumTerm() const;
    void setMinimumTerm(int32_t value);
    bool minimum_termIsSet() const;
    void unsetMinimum_term();
    /// <summary>
    /// 
    /// </summary>
    utility::string_t getName() const;
    void setName(utility::string_t value);
    bool nameIsSet() const;
    void unsetName();
    /// <summary>
    /// 
    /// </summary>
    utility::string_t getPrimarySku() const;
    void setPrimarySku(utility::string_t value);
    bool primary_skuIsSet() const;
    void unsetPrimary_sku();
    /// <summary>
    /// 
    /// </summary>
    utility::string_t getReactivationSku() const;
    void setReactivationSku(utility::string_t value);
    bool reactivation_skuIsSet() const;
    void unsetReactivation_sku();
    /// <summary>
    /// 
    /// </summary>
    utility::string_t getRecurringSku() const;
    void setRecurringSku(utility::string_t value);
    bool recurring_skuIsSet() const;
    void unsetRecurring_sku();
    /// <summary>
    /// 
    /// </summary>
    int32_t getRenewPeriod() const;
    void setRenewPeriod(int32_t value);
    bool renew_periodIsSet() const;
    void unsetRenew_period();
    /// <summary>
    /// 
    /// </summary>
    utility::string_t getRenewPeriodUnitOfTime() const;
    void setRenewPeriodUnitOfTime(utility::string_t value);
    bool renew_period_unit_of_timeIsSet() const;
    void unsetRenew_period_unit_of_time();
    /// <summary>
    /// 
    /// </summary>
    int32_t getSubscriptionId() const;
    void setSubscriptionId(int32_t value);
    bool subscription_idIsSet() const;
    void unsetSubscription_id();

protected:
    std::map<utility::string_t, std::shared_ptr<Property>> m_Additional_properties;
    bool m_Additional_propertiesIsSet;
utility::string_t m_Availability;
    bool m_AvailabilityIsSet;
int32_t m_Bill_grace_days;
    bool m_Bill_grace_daysIsSet;
bool m_Consolidated;
    bool m_ConsolidatedIsSet;
int32_t m_First_bill;
    bool m_First_billIsSet;
utility::string_t m_First_bill_unit_of_time;
    bool m_First_bill_unit_of_timeIsSet;
utility::string_t m_Id;
    bool m_IdIsSet;
utility::string_t m_Late_payment_sku;
    bool m_Late_payment_skuIsSet;
bool m_Locked;
    bool m_LockedIsSet;
int32_t m_Max_auto_renew;
    bool m_Max_auto_renewIsSet;
int32_t m_Max_bill_attempts;
    bool m_Max_bill_attemptsIsSet;
utility::string_t m_Migration_plan;
    bool m_Migration_planIsSet;
int32_t m_Minimum_term;
    bool m_Minimum_termIsSet;
utility::string_t m_Name;
    bool m_NameIsSet;
utility::string_t m_Primary_sku;
    bool m_Primary_skuIsSet;
utility::string_t m_Reactivation_sku;
    bool m_Reactivation_skuIsSet;
utility::string_t m_Recurring_sku;
    bool m_Recurring_skuIsSet;
int32_t m_Renew_period;
    bool m_Renew_periodIsSet;
utility::string_t m_Renew_period_unit_of_time;
    bool m_Renew_period_unit_of_timeIsSet;
int32_t m_Subscription_id;
    bool m_Subscription_idIsSet;
};

}
}
}
}

#endif /* SubscriptionPlan_H_ */
