/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator 2.2.3.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



#include "VideoGroupPropertyDefinitionResource.h"

namespace com {
namespace knetikcloud {
namespace client {
namespace model {

VideoGroupPropertyDefinitionResource::VideoGroupPropertyDefinitionResource()
{
    m_Max_height = 0;
    m_Max_heightIsSet = false;
    m_Max_length = 0;
    m_Max_lengthIsSet = false;
    m_Max_width = 0;
    m_Max_widthIsSet = false;
    m_Min_height = 0;
    m_Min_heightIsSet = false;
    m_Min_length = 0;
    m_Min_lengthIsSet = false;
    m_Min_width = 0;
    m_Min_widthIsSet = false;
}

VideoGroupPropertyDefinitionResource::~VideoGroupPropertyDefinitionResource()
{
}

void VideoGroupPropertyDefinitionResource::validate()
{
    // TODO: implement validation
}

web::json::value VideoGroupPropertyDefinitionResource::toJson() const
{
    web::json::value val = this->FileGroupPropertyDefinitionResource::toJson();

    if(m_Max_heightIsSet)
    {
        val[U("max_height")] = ModelBase::toJson(m_Max_height);
    }
    if(m_Max_lengthIsSet)
    {
        val[U("max_length")] = ModelBase::toJson(m_Max_length);
    }
    if(m_Max_widthIsSet)
    {
        val[U("max_width")] = ModelBase::toJson(m_Max_width);
    }
    if(m_Min_heightIsSet)
    {
        val[U("min_height")] = ModelBase::toJson(m_Min_height);
    }
    if(m_Min_lengthIsSet)
    {
        val[U("min_length")] = ModelBase::toJson(m_Min_length);
    }
    if(m_Min_widthIsSet)
    {
        val[U("min_width")] = ModelBase::toJson(m_Min_width);
    }

    return val;
}

void VideoGroupPropertyDefinitionResource::fromJson(web::json::value& val)
{
    this->FileGroupPropertyDefinitionResource::fromJson(val);

    if(val.has_field(U("max_height")))
    {
        setMaxHeight(ModelBase::int32_tFromJson(val[U("max_height")]));
    }
    if(val.has_field(U("max_length")))
    {
        setMaxLength(ModelBase::int32_tFromJson(val[U("max_length")]));
    }
    if(val.has_field(U("max_width")))
    {
        setMaxWidth(ModelBase::int32_tFromJson(val[U("max_width")]));
    }
    if(val.has_field(U("min_height")))
    {
        setMinHeight(ModelBase::int32_tFromJson(val[U("min_height")]));
    }
    if(val.has_field(U("min_length")))
    {
        setMinLength(ModelBase::int32_tFromJson(val[U("min_length")]));
    }
    if(val.has_field(U("min_width")))
    {
        setMinWidth(ModelBase::int32_tFromJson(val[U("min_width")]));
    }
}

void VideoGroupPropertyDefinitionResource::toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix) const
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix[namePrefix.size() - 1] != U('.'))
    {
        namePrefix += U(".");
    }

    if(m_Field_listIsSet)
    {
        if (m_Field_list.get())
        {
            m_Field_list->toMultipart(multipart, U("field_list."));
        }
        
    }
    multipart->add(ModelBase::toHttpContent(namePrefix + U("name"), m_Name));
    multipart->add(ModelBase::toHttpContent(namePrefix + U("required"), m_Required));
    multipart->add(ModelBase::toHttpContent(namePrefix + U("type"), m_Type));
    if(m_File_typeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + U("file_type"), m_File_type));
        
    }
    if(m_Max_countIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + U("max_count"), m_Max_count));
    }
    if(m_Max_file_sizeIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + U("max_file_size"), m_Max_file_size));
    }
    if(m_Min_countIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + U("min_count"), m_Min_count));
    }
    if(m_Max_heightIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + U("max_height"), m_Max_height));
    }
    if(m_Max_lengthIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + U("max_length"), m_Max_length));
    }
    if(m_Max_widthIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + U("max_width"), m_Max_width));
    }
    if(m_Min_heightIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + U("min_height"), m_Min_height));
    }
    if(m_Min_lengthIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + U("min_length"), m_Min_length));
    }
    if(m_Min_widthIsSet)
    {
        multipart->add(ModelBase::toHttpContent(namePrefix + U("min_width"), m_Min_width));
    }
}

void VideoGroupPropertyDefinitionResource::fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& prefix)
{
    utility::string_t namePrefix = prefix;
    if(namePrefix.size() > 0 && namePrefix[namePrefix.size() - 1] != U('.'))
    {
        namePrefix += U(".");
    }

    if(multipart->hasContent(U("field_list")))
    {
        if(multipart->hasContent(U("field_list")))
        {
            std::shared_ptr<PropertyFieldListResource> newItem(new PropertyFieldListResource());
            newItem->fromMultiPart(multipart, U("field_list."));
            setFieldList( newItem );
        }
    }
    setName(ModelBase::stringFromHttpContent(multipart->getContent(U("name"))));
    setRequired(ModelBase::boolFromHttpContent(multipart->getContent(U("required"))));
    setType(ModelBase::stringFromHttpContent(multipart->getContent(U("type"))));
    if(multipart->hasContent(U("file_type")))
    {
        setFileType(ModelBase::stringFromHttpContent(multipart->getContent(U("file_type"))));
    }
    if(multipart->hasContent(U("max_count")))
    {
        setMaxCount(ModelBase::int32_tFromHttpContent(multipart->getContent(U("max_count"))));
    }
    if(multipart->hasContent(U("max_file_size")))
    {
        setMaxFileSize(ModelBase::int64_tFromHttpContent(multipart->getContent(U("max_file_size"))));
    }
    if(multipart->hasContent(U("min_count")))
    {
        setMinCount(ModelBase::int32_tFromHttpContent(multipart->getContent(U("min_count"))));
    }
    if(multipart->hasContent(U("max_height")))
    {
        setMaxHeight(ModelBase::int32_tFromHttpContent(multipart->getContent(U("max_height"))));
    }
    if(multipart->hasContent(U("max_length")))
    {
        setMaxLength(ModelBase::int32_tFromHttpContent(multipart->getContent(U("max_length"))));
    }
    if(multipart->hasContent(U("max_width")))
    {
        setMaxWidth(ModelBase::int32_tFromHttpContent(multipart->getContent(U("max_width"))));
    }
    if(multipart->hasContent(U("min_height")))
    {
        setMinHeight(ModelBase::int32_tFromHttpContent(multipart->getContent(U("min_height"))));
    }
    if(multipart->hasContent(U("min_length")))
    {
        setMinLength(ModelBase::int32_tFromHttpContent(multipart->getContent(U("min_length"))));
    }
    if(multipart->hasContent(U("min_width")))
    {
        setMinWidth(ModelBase::int32_tFromHttpContent(multipart->getContent(U("min_width"))));
    }
}

int32_t VideoGroupPropertyDefinitionResource::getMaxHeight() const
{
    return m_Max_height;
}


void VideoGroupPropertyDefinitionResource::setMaxHeight(int32_t value)
{
    m_Max_height = value;
    m_Max_heightIsSet = true;
}
bool VideoGroupPropertyDefinitionResource::maxHeightIsSet() const
{
    return m_Max_heightIsSet;
}

void VideoGroupPropertyDefinitionResource::unsetMax_height()
{
    m_Max_heightIsSet = false;
}

int32_t VideoGroupPropertyDefinitionResource::getMaxLength() const
{
    return m_Max_length;
}


void VideoGroupPropertyDefinitionResource::setMaxLength(int32_t value)
{
    m_Max_length = value;
    m_Max_lengthIsSet = true;
}
bool VideoGroupPropertyDefinitionResource::maxLengthIsSet() const
{
    return m_Max_lengthIsSet;
}

void VideoGroupPropertyDefinitionResource::unsetMax_length()
{
    m_Max_lengthIsSet = false;
}

int32_t VideoGroupPropertyDefinitionResource::getMaxWidth() const
{
    return m_Max_width;
}


void VideoGroupPropertyDefinitionResource::setMaxWidth(int32_t value)
{
    m_Max_width = value;
    m_Max_widthIsSet = true;
}
bool VideoGroupPropertyDefinitionResource::maxWidthIsSet() const
{
    return m_Max_widthIsSet;
}

void VideoGroupPropertyDefinitionResource::unsetMax_width()
{
    m_Max_widthIsSet = false;
}

int32_t VideoGroupPropertyDefinitionResource::getMinHeight() const
{
    return m_Min_height;
}


void VideoGroupPropertyDefinitionResource::setMinHeight(int32_t value)
{
    m_Min_height = value;
    m_Min_heightIsSet = true;
}
bool VideoGroupPropertyDefinitionResource::minHeightIsSet() const
{
    return m_Min_heightIsSet;
}

void VideoGroupPropertyDefinitionResource::unsetMin_height()
{
    m_Min_heightIsSet = false;
}

int32_t VideoGroupPropertyDefinitionResource::getMinLength() const
{
    return m_Min_length;
}


void VideoGroupPropertyDefinitionResource::setMinLength(int32_t value)
{
    m_Min_length = value;
    m_Min_lengthIsSet = true;
}
bool VideoGroupPropertyDefinitionResource::minLengthIsSet() const
{
    return m_Min_lengthIsSet;
}

void VideoGroupPropertyDefinitionResource::unsetMin_length()
{
    m_Min_lengthIsSet = false;
}

int32_t VideoGroupPropertyDefinitionResource::getMinWidth() const
{
    return m_Min_width;
}


void VideoGroupPropertyDefinitionResource::setMinWidth(int32_t value)
{
    m_Min_width = value;
    m_Min_widthIsSet = true;
}
bool VideoGroupPropertyDefinitionResource::minWidthIsSet() const
{
    return m_Min_widthIsSet;
}

void VideoGroupPropertyDefinitionResource::unsetMin_width()
{
    m_Min_widthIsSet = false;
}

}
}
}
}

