/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator 2.3.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * WebsocketSendMessageEvent.h
 *
 * 
 */

#ifndef WebsocketSendMessageEvent_H_
#define WebsocketSendMessageEvent_H_


#include "BroadcastableEvent.h"
#include <cpprest/details/basic_types.h>
#include "Object.h"
#include <vector>

namespace com {
namespace knetikcloud {
namespace client {
namespace model {

/// <summary>
/// 
/// </summary>
class  WebsocketSendMessageEvent
    : public BroadcastableEvent
{
public:
    WebsocketSendMessageEvent();
    virtual ~WebsocketSendMessageEvent();

    /////////////////////////////////////////////
    /// ModelBase overrides

    void validate() override;

    web::json::value toJson() const override;
    void fromJson(web::json::value& json) override;

    void toMultipart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) const override;
    void fromMultiPart(std::shared_ptr<MultipartFormData> multipart, const utility::string_t& namePrefix) override;

    /////////////////////////////////////////////
    /// WebsocketSendMessageEvent members

    /// <summary>
    /// 
    /// </summary>
    std::shared_ptr<Object> getContent() const;
    bool contentIsSet() const;
    void unsetContent();
    void setContent(std::shared_ptr<Object> value);
    /// <summary>
    /// 
    /// </summary>
    std::vector<utility::string_t>& getUsernames();
    bool usernamesIsSet() const;
    void unsetUsernames();
    void setUsernames(std::vector<utility::string_t> value);

protected:
    std::shared_ptr<Object> m_Content;
    bool m_ContentIsSet;
    std::vector<utility::string_t> m_Usernames;
    bool m_UsernamesIsSet;
};

}
}
}
}

#endif /* WebsocketSendMessageEvent_H_ */
