/**
 * Knetik Platform API Documentation latest 
 * This is the spec for the Knetik API.  Use this in conjunction with the documentation found at https://knetikcloud.com.
 *
 * OpenAPI spec version: latest 
 * Contact: support@knetik.com
 *
 * NOTE: This class is auto generated by the swagger code generator 2.3.0-SNAPSHOT.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * DevicesApi.h
 *
 * 
 */

#ifndef DevicesApi_H_
#define DevicesApi_H_


#include "ApiClient.h"

#include "DeviceResource.h"
#include "PageResource«DeviceResource».h"
#include "Result.h"
#include "SimpleUserResource.h"
#include <vector>
#include <cpprest/details/basic_types.h>

namespace com {
namespace knetikcloud {
namespace client {
namespace api {

using namespace com::knetikcloud::client::model;

class  DevicesApi
{
public:
    DevicesApi( std::shared_ptr<ApiClient> apiClient );
    virtual ~DevicesApi();
    /// <summary>
    /// Add device users
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="userResources">userResources</param>/// <param name="id">id</param>
    pplx::task<std::shared_ptr<DeviceResource>> addDeviceUsers(std::vector<std::shared_ptr<SimpleUserResource>> userResources, int32_t id);
    /// <summary>
    /// Create a device
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="device">device</param>
    pplx::task<std::shared_ptr<DeviceResource>> createDevice(std::shared_ptr<DeviceResource> device);
    /// <summary>
    /// Delete a device
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="id">id</param>
    pplx::task<void> deleteDevice(int32_t id);
    /// <summary>
    /// Delete a device user
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="id">The id of the device</param>/// <param name="userId">The user id of the device user</param>
    pplx::task<void> deleteDeviceUser(int32_t id, int32_t userId);
    /// <summary>
    /// Delete all device users
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="id">The id of the device</param>/// <param name="filterId">Filter for device users to delete with a user id in a given comma separated list of ids (optional)</param>
    pplx::task<void> deleteDeviceUsers(int32_t id, utility::string_t filterId);
    /// <summary>
    /// Get a single device
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="id">id</param>
    pplx::task<std::shared_ptr<DeviceResource>> getDevice(int32_t id);
    /// <summary>
    /// List and search devices
    /// </summary>
    /// <remarks>
    /// Get a list of devices with optional filtering
    /// </remarks>
    /// <param name="filterMake">Filter for devices with specified make (optional)</param>/// <param name="filterModel">Filter for devices with specified model (optional)</param>/// <param name="size">The number of objects returned per page (optional, default to 25)</param>/// <param name="page">The number of the page returned, starting with 1 (optional, default to 1)</param>/// <param name="order">A comma separated list of sorting requirements in priority order, each entry matching PROPERTY_NAME:[ASC|DESC] (optional, default to id:ASC)</param>
    pplx::task<std::shared_ptr<PageResource«DeviceResource»>> getDevices(utility::string_t filterMake, utility::string_t filterModel, int32_t size, int32_t page, utility::string_t order);
    /// <summary>
    /// Update a device
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="device">device</param>/// <param name="id">id</param>
    pplx::task<std::shared_ptr<DeviceResource>> updateDevice(std::shared_ptr<DeviceResource> device, int32_t id);

protected:
    std::shared_ptr<ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* DevicesApi_H_ */

